### PR TITLE
Add: Update System Functions

### PR DESCRIPTION
**Pull request by BigoStream**
Add: Added a way to update system programs via command line.

### CODE REVIEW

**Comment by REALSDEALS** [comment]
There is still a problem/bugg in the code that you have added.

There a 2 functions with the number '8,' this means that the script doesn't know which one of the '8's' it has to run. Resulting in a crash.

Can you look at it? 
Otherwise I could still fix it.

**Comment by BigoStream** [comment]
I will get right back to it!

**Comment by BigoStream** [comment]
It should be addressed now.

**Comment by REALSDEALS** [comment]
I still have issues running function '8,' will check later for myself what the issue might be.

**Comment by REALSDEALS** [comment]
I have looked at the code and it seems to be an issue with the 'taggs' for calling back the expected feature. I will accept the pull-request and re-write it. Not a big issue, just a small rework.

Thanks for the effort!

**Pull request merged**
